version: '3.4'
services:
  client: 
    build: /client
    ports:
      - 3001:3001
    depends_on:
      - redis
  server: 
    build: /backend
    ports:
      - 3000:3000
  redis: 
    image: redis
    ports:
      - 6379:6379  